apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sova
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://sova.danesjenovdan.si, https://sova.djnd.si, https://sova.lb.djnd.si"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sova.lb.djnd.si
      secretName: sova-tls
    - hosts:
        - sova.danesjenovdan.si
        - sova.djnd.si
      secretName: sova-djnd-tls
  rules:
    - host: sova.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sova
                port:
                  number: 80
    - host: sova.danesjenovdan.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sova
                port:
                  number: 80
    - host: sova.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sova
                port:
                  number: 80
