apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sova
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sova.lb.djnd.si
      secretName: sova-tls
  rules:
    - host: sova.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sova
                port:
                  number: 80
