apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sova
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: sova
    newName: rg.fr-par.scw.cloud/djnd/sova
    newTag: '33e4662a9fedf47c8a42c1faf1692a588f3f5dc1'
