apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sova
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: sova
    newName: rg.fr-par.scw.cloud/djnd/sova
    newTag: 'ee0f8cb36517594528e07bacc30fd7800fb516d6'
